In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)



[1 2 3]


In [3]:
b=np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
b=np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
b=np.full((3,4),7)
print(b)
print(b.size)
print(b[1:2,1:3])

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
12
[[7 7]]


In [6]:
b=np.arange(0,10,2)
print(b)

[0 2 4 6 8]


In [7]:
b=np.linspace(0,1,5)
print(b)

[0.   0.25 0.5  0.75 1.  ]


In [9]:
b=np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
a=np.array([10,20,30,40,50])
print(a[::2])
print(a[a>25])
print(a[[0,1,4,2]])

[10 30 50]
[30 40 50]
[10 20 50 30]


In [32]:
a = np.array([1, 2, 3])

b = np.array([10, 20, 30, 40])

In [33]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [13]:
# broadcasting
import numpy as np
a=np.array([[1],
            [2],
            [3]])
print(a.shape)

(3, 1)


In [7]:
b=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(b.shape)

(3, 3)


In [14]:
print(a+b)

[[11 21 31]
 [42 52 62]
 [73 83 93]]


In [ ]:
np.random.seed(10)
print(np.random.rand(3))



[0.77132064 0.02075195 0.63364823]


In [24]:
rng = np.random.default_rng(10)

print(rng.random(3))

[0.95600171 0.20768181 0.82844489]


In [25]:
np.random.seed(42)
print(np.random.randint(1,10,5))

[7 4 8 5 7]


In [26]:
rng=np.random.default_rng(42)
print(rng.integers(1,10,5))

[1 7 6 4 4]


In [27]:
np.random.rand(3,4)

array([[4.45832753e-01, 9.99749158e-02, 4.59248892e-01, 3.33708611e-01],
       [1.42866818e-01, 6.50888473e-01, 5.64115790e-02, 7.21998772e-01],
       [9.38552709e-01, 7.78765841e-04, 9.92211559e-01, 6.17481510e-01]])

In [32]:
np.random.randn(3,4)

array([[ 0.69844026,  0.17360206,  0.66228451,  0.24112216],
       [-0.16820509,  1.16476865, -0.24574769, -0.76966777],
       [ 1.21217234,  1.2334968 , -1.57415529,  0.63795294]])

In [38]:
np.random.randint(0,10,(3,4))

array([[0, 3, 3, 4],
       [6, 6, 3, 6],
       [2, 5, 1, 9]])

In [ ]:
np.random.choice(a)

In [44]:
a = np.array([1,2,3,4,5,6,7,8])

# a.reshape(2, 3) # [[1,2,3],[4,5,6]]

a.reshape(-1, 2) # auto-infer rows → (2,3)

# a.reshape(3, -1) # auto-infer cols → (3,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
a=np.array([[1,2],[3,4]])   
# b=a.flatten()
# print(b)
b=a.ravel()
print(b)
print(a)

[1 2 3 4]
[[1 2]
 [3 4]]
